### ISSUE TITLE
[bug-reporter] [android] app crashed when taking screenshot

### ISSUE THREAD

**Issue by cindyip** [USThing/USThing_Master#236]
### Expected behavior
take screenshot
### Actual behavior
app crashed
### Steps to reproduce
settings > feedback > screenshot > camera button
### Environment
- App Version: v3.30Dev
- Phone Model: Sony Xperia Tablet
- OS Version: android 6.0.1
- OS Language: chinese

**Comment by Camerash** [comment]
Should be fixed in v3.40

**Comment by cindyip** [comment]
sorry bug fix can't be verified. still happens on v4.0.2dev. 
current behavior: settings > feedback > screenshot > camera button > app crashed and closed > after clicking 'confirm' on the dialog 'usthing app has stopped', wait 2 seconds, bug reporter suddenly pops up again, but it's broken, the buttons on the screen don't work anymore
