### ISSUE TITLE
[Android] USThings cannot set username

### ISSUE THREAD

**Issue by christyyeung** [USThing/USThing_Master#4]
### App Version and device
Android

### Expected behavior

Message can be sent at desired username after setting it

### Actual behavior
Message sent as random guest after setting username, how disappointing :(

**Comment by Camerash** [comment]
tszkanlo/USThing_Android#41
Should be fixed on v2.2.2

**Comment by c-samuel** [comment]
Checked on 27/3, seems still cannot set username in v2.22, and the profile name does not match with the USThings one. Will fix this in v2.3.

**Comment by chihimng** [comment]
feature discontinued
